version: '3'

services: 
  app: 
    container_name: iex-stock-market-api_app
    build: .
    ports: 
      - 3000:3000
    entrypoint: 'dockerize -wait tcp://db:3306/ -timeout 40s ./.docker/entrypoint.sh'
    volumes: 
      - .:/home/node/app
    depends_on: 
      - db

  db: 
    container_name: iex-stock-market-api_db
    build: ./.docker/mysql/
    ports: 
      - 3306:3306
    restart: on-failure
    env_file: ./.docker/mysql/.env
    volumes: 
      - ./.docker/dbdata:/var/lib/mysql
